### ISSUE TITLE
error after update tailwind to 3

### ISSUE THREAD

**Issue by Saeeed-B** [Meteor-Community-Packages/meteor-postcss#53] opened 2021-12-13 07:48 UTC
@StorytellerCZ 

![image](https://user-images.githubusercontent.com/36485982/145772392-52156c77-40c1-4266-a64d-994945b2c687.png)

**Comment by Saeeed-B** [comment] 2021-12-13 07:49
this is .postcssrc.js

![image](https://user-images.githubusercontent.com/36485982/145772523-c3a1cbad-85dd-4187-84fc-e437305c5095.png)

**Comment by csellis** [comment] 2021-12-13 15:29
You haven't defined `NODE_ENV`. This is a plain old JS error. console.log `ctx` to look at the shape of the data when you build.

**Comment by Saeeed-B** [comment] 2021-12-13 15:36
@csellis How should I define it?
Where exactly does ctx come from? Does it come from environmental variables or from the package. json?

**Comment by Saeeed-B** [comment] 2021-12-13 15:40
@csellis 
On the other hand, after defining the environmental variable `NODE_ENV`, I get this error.

![145774792-a74b5558-c691-46db-8d73-33e5740a015e](https://user-images.githubusercontent.com/36485982/145842032-42fb79fb-34e4-4043-86f4-4e6e506878de.png)

**Comment by StorytellerCZ** [comment] 2021-12-15 18:11
This is a duplicate of #51

**Closed as completed by StorytellerCZ** 2021-12-15 18:11 UTC
