### ISSUE TITLE
Error After Update to 2.0.7

### ISSUE THREAD

**Issue by Saeeed-B** [Meteor-Community-Packages/meteor-postcss#49] opened 2021-08-03 10:44 UTC
@StorytellerCZ hi
Error After Update to 2.0.7:
I have tested the software many times. This problem is only due to the update to the new version.

![image](https://user-images.githubusercontent.com/36485982/128002768-4c03f7d7-df5a-45b6-9680-848941c9051b.png)

**Comment by Saeeed-B** [comment] 2021-08-03 11:20
These bugs took hours of our time, please follow up.

**Comment by Saeeed-B** [comment] 2021-08-06 06:22
@StorytellerCZ  ?

**Comment by StorytellerCZ** [comment] 2021-08-09 13:03
I can only see dependencies updates and one fix for Cordova for 2.0.7
In the case of the error you are getting it means that `file._source.url` is undefined. :thinking: 
Can you provide a reproduction repo or form locally and add a log around there to see what is the input you are getting?

**Comment by flean** [comment] 2021-08-20 23:10
I'm having a similar issue too, I can't deploy to galaxy anymore. How do we fix this?

`Errors prevented deploying:
While minifying app stylesheet:               
packages/minifier-postcss/plugin/minify-css.js:137:56: Cannot read property 'replace' of null
at packages/minifier-postcss/plugin/minify-css.js:137:56
at Array.map (<anonymous>)
at mergeCss (packages/minifier-postcss/plugin/minify-css.js:119:23)
at CssToolsMinifier.processFilesForBundle (packages/minifier-postcss/plugin/minify-css.js:89:18)`

I returned to version 2.0.6 and it works

**Comment by StorytellerCZ** [comment] 2021-08-21 08:49
@flean can you please provide a quick reproduction or add some logging so that we know what input you are getting?

**Comment by bslocombe** [comment] 2021-08-27 04:18
Same issue for us: Dumping one of the files it iterates on, looks like the _source.url is null for some files that are imported from NPM packages. 

Commit https://github.com/Meteor-Community-Packages/meteor-postcss/commit/7049792ae11da20342fd1ff8118a76df754c15b3  seems to be the issue.  Perhaps this is simply just checking for the case the _source.url is null but not sure why you would want to change the url for cordova builds manually anyway?

app/node_modules/@fullcalendar/common/main.css{
  "_source": {
    "info": "resource /node_modules/@fullcalendar/common/main.css",
    "sourceMap": null,
    "sourceMapRoot": null,
    "targetPath": "app/node_modules/@fullcalendar/common/main.css",
    "url": null,
    "urlPrefix": "",
    "cacheable": false,
    "nodeModulesDirectories": {},
    "assets": null,
    "_contents": {
      "type": "Buffer",
      "data": [
        //commented out Buffer
      ]
    },
    "_inputHash": "23de08280f8908cca3442ed92653bff3ad8d724c",
    "_hash": "dcd19a1595e6437bd7b52c17093d4fa07807b02c",
    "_sri": "5MFsuWkSlnuExv3jYZtiQvxqYZsEhldd99/ax+ucjptz44SoOdkL1dRIIUcOPn9GkjnalhY9ld+fBvv4jbKIuw=="
  },
  "_arch": "web.browser.legacy",
  "_minifiedFiles": []

**Comment by StorytellerCZ** [comment] 2021-08-27 09:42
Let's go for the simplest solution first by adding a conditional there.

**Comment by StorytellerCZ** [comment] 2021-12-12 16:59
@Saeeed-B forgot to ask if this is resolved for you.

**Comment by Saeeed-B** [comment] 2021-12-12 17:00
Now yes

**Comment by StorytellerCZ** [comment] 2021-12-12 17:03
Great! I will close this for now then.

**Closed as completed by StorytellerCZ** 2021-12-12 17:03 UTC
